---
galaxy_info:
  role_name: vm_hot_plug
  author: OpenShift Virtualization Migration Contributors
  description: Hot Plug Virtual Machine resources.
  company: ""
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - openshift
    - virtualization
    - kubevirt
    - hotplug
dependencies: []
...
